# NOT in use/ NOT WORKING

version: "3"

services:

  spring-boot-app:
    #not recommend container name when we are scaling
    container_name: docker-mysql
    image: mydockerapp
    restart: always
    build: .
    ports:
      - '9900:8080'
    environment:
      MYSQL_HOST: test
      MYSQL_USER: sys
      MYSQL_PASSWORD: 1234
      MYSQL_PORT: 3306

  mysqldb:
    container_name: docker-mysql
    image: mysql:8.0.29-debian
    #external port:internal port
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: sys
      MYSQL_PASSWORD: 1234